#!/bin/bash
set -o noglob
# Verification 
# Function Count Files
# Usage:
#     countFiles <folder> <filetype>
countFiles ()	{
	printf `find $1 -iname $2 | wc -l`
	return `find $1 -iname $2 | wc -l`
}

# Function Count Files
# Usage:
#     verifyFileCount <folder1> <folder2> <filetype>
lhs=$(countFiles $1 $3)
rhs=$(countFiles $2 $3)
if [ $lhs == $rhs ]
	then 
		printf "$lhs Files Copied from $1 to $2 Successfully..." 
	else 
		printf "Error in Copying All/Some $3 Files !!!" 
fi

